services:
  - type: web
    name: uniprephub-web
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: bash ./start-render.sh
    autoDeploy: true

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        sync: false

      - key: APP_URL
        sync: false

      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        value: "3306"

      - key: DB_DATABASE
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: CACHE_DRIVER
        value: file

      - key: SESSION_DRIVER
        value: file

      - key: QUEUE_CONNECTION
        value: sync

      - key: FILESYSTEM_DISK
        value: public

      - key: LOG_CHANNEL
        value: stack

      - key: VITE_APP_URL
        sync: false